<?php

/**
 *  General template for displaying group of blocks devided into sections
 */

$group = $block->getGroupName();
$groupCss = $block->getGroupCss();
$groupBehavior = $block->getGroupBehaviour() ? $block->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')):?>
        <?php $layout = $block->getLayout(); ?>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html) && ($block->getUseForce() != true)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="collapse navbar-collapse d-lg-flex justify-content-lg-end <?= /* @escapeNotVerified */ $groupCss ?>-item-content" id="<?= /* @escapeNotVerified */ $alias ?>" id="navbarNav" data-role="content"><?= /* @escapeNotVerified */ $html ?></div>
            <?php endforeach;?>
        </ul>
    </div>
<?php endif; ?>