<div id="ves-header"class="ves-header">
    <div class="row no-margin">
        <div class="col-md-2 col-sm-3 col-xs-5 custom-logo">
            <?php echo $this->getChildHtml("logo"); ?>
        </div>
        <div class="col-md-7 col-sm-5 col-xs-2">
            <?php echo $this->getChildHtml('catalog.topnav'); ?>
            <!-- <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('fasony-menutop')->toHtml();?> -->
        </div>

    </div>
</div>

